version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
  web:
    build: .
    environment:
      DATABASE_URL: mysql+pymysql://myuser:mypassword@db/mydatabase
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  mysql_data:
